baseurl = "https://limbo1996.github.io/home/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "WangX | 王轩"
theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
enableGitInfo = false
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/limbo1996"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/vitae/"
    weight = 4   
    
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 5

[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 6

[params]
    description = "Website of WangXuan"
    enableGitalk = true
    customJS = ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js", "js/header-link.js"]
    githubContentURL = "https://github.com/limbo1996/home/edit/master/content/"
    highlightjsVersion = "9.12.0"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsTheme = "Xcode"
    dateFormat = "2006-01-02, Mon" 

[params.footer]
    home = "Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/) &copy; [Shixiang Wang](/) 2017 - 2020"
    en   = "[<i class='far fa-envelope fa-1x'></i>](mailto:w_shixiang@163.com) &middot; [<i class='fab fa-github fa-1x'></i>](https://github.com/ShixiangWang) &middot; [<i class='fab fa-stack-overflow fa-1x'></i>](https://stackoverflow.com/users/7662327/shixiang-wang) &middot; [<i class='ai ai-google-scholar ai-1x'></i>](https://scholar.google.com/citations?user=FvNp0NkAAAAJ&hl=en) &middot; [<i class='ai ai-orcid ai-1x'></i>](https://orcid.org/0000-0001-9855-7357) &middot; [<i class='ai ai-researchgate ai-1x'></i>](https://www.researchgate.net/profile/Wang_Shixiang4) <br> Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/) &copy; [WangXuan](/) 2020"
    cn   = "[<i class='far fa-envelope fa-1x'></i>](mailto:w_shixiang@163.com) &middot; [<i class='fab fa-github fa-1x'></i>](https://github.com/ShixiangWang) &middot; [<i class='fab fa-stack-overflow fa-1x'></i>](https://stackoverflow.com/users/7662327/shixiang-wang) &middot; [<i class='ai ai-google-scholar ai-1x'></i>](https://scholar.google.com/citations?user=FvNp0NkAAAAJ&hl=zh-CN) &middot; [<i class='ai ai-orcid ai-1x'></i>](https://orcid.org/0000-0001-9855-7357) &middot; [<i class='ai ai-researchgate ai-1x'></i>](https://www.researchgate.net/profile/Wang_Shixiang4) <br> 本站由 [Hugo](https://gohugo.io) 和 [Blogdown](https://bookdown.org/yihui/blogdown/) 强力驱动 &copy; [王轩](/) 2020"

[params.author]
    en = "WangXuan"
    cn = "王轩"

[params.categories]
    en = "Categories"
    cn = "分类"

[params.tags]
    en = "Tags"
    cn = "标签"
[params.lang.edit]
    cn = "编辑"
[params.lang.license]
    cn = "版权"
[params.lang.subscribe]
    cn = "订阅"
