baseurl = "https://limbo1996.github.io/home/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "WangX | 王轩"
theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
enableGitInfo = false
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "English"
    url = "/en／"
    weight = 1

[[menu.main]]
    name = "中文"
    url = "/cn/"
    weight = 2

[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2

[[menu.en]]
    name = "Blog"
    url = "/en/post/"
    weight = 3

[[menu.en]]
    name = "Software"
    url = "/en/tools/"
    weight = 4

[[menu.en]]
    name = "CV"
    url = "/en/cv-en/wx"
    weight = 5

[[menu.en]]
    name = "Categories"
    url = "/categories/"
    weight = 6

[[menu.en]]
    name = "Tags"
    url = "/tags/"
    weight = 7

[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 8

[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2

[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 3

[[menu.cn]]
    name = "分类"
    url = "/categories/"
    weight = 4

[[menu.cn]]
    name = "标签"
    url = "/tags/"
    weight = 5

[params]
    description = "Website of WangXuan"
    enableGitalk = true
    customJS = ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js", "js/header-link.js"]
    githubContentURL = "https://github.com/limbo1996/home/edit/master/content/"
    highlightjsVersion = "9.12.0"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsTheme = "Xcode"
    dateFormat = "2006-01-02, Mon" 


