baseurl = "https://limbo1996.github.io/home/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "WangX | 王轩"
theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
enableGitInfo = false
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "关于"
    url = "/main/about/"
    weight = 1

[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

[params]
    description = "Website of WangXuan"
    enableGitalk = true
    customJS = ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js", "js/header-link.js"]
    githubContentURL = "https://github.com/limbo1996/home/edit/master/content/"
    highlightjsVersion = "9.12.0"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsTheme = "Xcode"
    dateFormat = "2006-01-02, Mon" 


