baseurl = "https://limbo1996.github.io/home/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "WangX | 王轩"
theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
enableGitInfo = false
publishDir = "docs"

[[menu.main]]
    name = "English"
    url = "/en／"
    weight = 1

[[menu.main]]
    name = "中文"
    url = "/cn/"
    weight = 2

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2

[[menu.en]]
    name = "Blog"
    url = "/en/post/"
    weight = 3

[[menu.en]]
    name = "Software"
    url = "/en/tools/"
    weight = 4

[[menu.en]]
    name = "CV"
    url = "/en/cv-en/Shixiang"
    weight = 6

[[menu.en]]
    name = "Categories"
    url = "/categories/"
    weight = 7

[[menu.en]]
    name = "Tags"
    url = "/tags/"
    weight = 8

[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 9

[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2

[[menu.cn]]
    name = "博客"
    url = "/cn/post/"
    weight = 3

[[menu.cn]]
    name = "读书"
    url = "/cn/read/"
    weight = 4

[[menu.cn]]
    name = "写作"
    url = "/cn/writing"
    weight = 5

[[menu.cn]]
    name = "研究"
    url = "/cn/research/"
    weight = 6

[[menu.cn]]
    name = "工具"
    url = "/cn/tools/"
    weight = 7

[[menu.cn]]
    name = "简历"
    url = "/cn/cv-cn/Shixiang"
    weight = 8

[[menu.cn]]
    name = "公众号"
    url = "/logo/qrcode.jpg"
    weight = 9

[[menu.cn]]
    name = "知乎"
    url = "https://www.zhihu.com/people/shixiangwang"
    weight = 10

[[menu.cn]]
    name = "推荐阅读"
    url = "/cn/mark"
    weight = 11

[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 12

[[menu.cn]]
    name = "分类"
    url = "/categories/"
    weight = 13

[[menu.cn]]
    name = "标签"
    url = "/tags/"
    weight = 14
