baseurl = "https://limbo1996.github.io/home/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "WangX | 王轩"
theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
enableGitInfo = false
publishDir = "docs"

[[menu.main]]
    name = "English"
    url = "/en／"
    weight = 1

[[menu.main]]
    name = "中文"
    url = "/cn/"
    weight = 2

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2

[[menu.en]]
    name = "Blog"
    url = "/en/post/"
    weight = 3

[[menu.en]]
    name = "Software"
    url = "/en/tools/"
    weight = 4

[[menu.en]]
    name = "CV"
    url = "/en/cv-en/Shixiang"
    weight = 6

[[menu.en]]
    name = "Categories"
    url = "/categories/"
    weight = 7

[[menu.en]]
    name = "Tags"
    url = "/tags/"
    weight = 8

[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 9

[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2

[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 12

[[menu.cn]]
    name = "分类"
    url = "/categories/"
    weight = 13

[[menu.cn]]
    name = "标签"
    url = "/tags/"
    weight = 14
